# Generated by Django 4.2.27 on 2026-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=20)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=128)),
                ('listing_type', models.CharField(choices=[('house', 'House'), ('car', 'Car')], max_length=10)),
                ('listing_id', models.CharField(db_index=True, max_length=128)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='', max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['listing_type', 'listing_id'], name='upload_uplo_listing_bcc255_idx'), models.Index(fields=['user_uid', 'uploaded_at'], name='upload_uplo_user_ui_fcabaf_idx')],
            },
        ),
    ]
